# -*- coding: utf-8 -*-
"""
Created on Fri May 31 14:16:16 2024

@author: Nevermore
"""
# This is the third file in a very long list of files

import pandas as pd

minor_blood_fallout = pd.DataFrame({"level":["minor","minor","minor","minor",
                                             "minor","minor","minor","minor",
                                             "minor","minor"],
                                    "kind":["blood","blood","blood","blood",
                                            "blood","blood","blood","blood",
                                            "blood","blood"],
                                    "name":["BATTERED","BLEEDING","DISARMED",
                                            "FURIOUS","LIMPING","RINGING HEAD",
                                            "SHATTERED","SPITTING TEETH",
                                            "TIRED","WINDED"],
                                    "description":["Your dominant hand is injured; you can bandage it up and stop the bleeding, but it’s of limited use for the time being. Any offensive action you make in combat becomes Risky; any tasks that require fine dexterity are out of the question.",
                                                   "At the end of each situation where you have this fallout, mark D4 stress to Blood.",
                                                   "You drop and lose whatever you’re holding, leaving you defenceless; you inflict D4 stress in combat until you source a weapon. If you’re somewhere precarious, you might lose the item forever.",
                                                   "You’re hurt, short-tempered and perceive sleights everywhere. You cannot help another character by adding a dice to their roll.",
                                                   "You’re slowed. If someone or something attacks your party, they’ll attack you first. If there’s any question over who arrives last, it’s you. All checks involving rapid or stealthy movement become Risky.",
                                                   "Your head swims and you taste blood in your mouth. The next action you take is Dangerous, the one after that is Risky, and then you remove this fallout as your head clears.",
                                                   "Your armour is no longer of use. You cannot use Blood Protection.",
                                                   "Any action that requires you to speak or look respectable is Risky.",
                                                   "You’re weary; you’re going to make bad decisions and snap at your friends. You cannot gain extra dice from skills.",
                                                   "When you attack with melee weapons, decrease stress inflicted by one dice size."],
                                    "duration":["Ongoing","Ongoing",
                                                "Immediate","Ogoing",
                                                "Ongoing","Immediate",
                                                "Ongoing","Ongoing","Ongoing",
                                                "Ongoing"]})

minor_mind_fallout = pd.DataFrame({"level":["minor","minor","minor","minor",
                                            "minor","minor","minor","minor",
                                            "minor"],
                                   "kind":["mind","mind","mind","mind","mind",
                                           "mind","mind","mind","mind"],
                                   "name":["CLOUDED","CREEPY",
                                           "COLLATERAL MAGIC","FASCINATION",
                                           "FIGMENT","SHAKEN",
                                           "TAKE THE EDGE OFF","VULNERABLE",
                                           "WEIRD"],
                                   "description":["Your mind starts to shut down in an attempt to protect itself; you can’t think straight and sensations are dulled. You cannot gain extra dice from Domains.",
                                                  "You react in a strange way that weirds out your friends – tell us how. Any friendly character who sees you do it marks D4 stress to Mind.",
                                                  "Your panicked mind breaks for a second and reforms in an arcane pattern; down here, the old magics of blood and bone work better than they do on the surface. You immediately cast AETHERIC SCOURGE on a nearby ally, but mark no stress for doing so. This fallout can be upgraded (see AETHERIC RESONANCE).",
                                                  "You become obsessed with a strange topic – usually whatever caused the fallout. You must try and learn more about it, first hand if possible. Whenever you attempt to learn more about your weird fascination, roll with mastery. If you have the opportunity to learn about it and you refuse, mark D4 stress to Mind.",
                                                  "You lose track of what’s real and what’s not. The GM picks a Minor fallout from a different resistance and tells you have it. Until this fallout is removed, you’re convinced you’re suffering from the fallout (no matter what others tell you) and suffer from all appropriate effects.",
                                                  "You panic and fall back on your primitive impulses. The GM chooses one: Fight (attack the problem in an attempt to destroy it), Flight (get away from the problem by any means necessary) or Freeze (do not act, putting yourself in danger). At the end of the situation, remove this fallout.",
                                                  "You can’t get your head right until you have a drink (or something stronger). Until you reach a landmark with access to intoxicants and render yourself insensible, roll two dice when you mark stress to Mind and pick the higher. Can be upgraded to ADDICT.",
                                                  "You feel small, shaken and scared. You cannot use Mind protection.",
                                                  "You do something unsettling that bothers normal people – obsessive behaviour, singing to yourself, fulfilling a strange compulsion at inappropriate times. At the earliest opportunity, the GM can declare that your weirdness puts a useful NPC off you (and probably your allies, too)."],
                                   "duration":["Ongoing","Immediate",
                                               "Immediate","Ogoing",
                                               "Ongoing","Immediate",
                                               "Ongoing","Ongoing",
                                               "Immediate, Ongoing"]})

minor_echo_fallout = pd.DataFrame({"level":["minor","minor","minor","minor",
                                            "minor","minor","minor","minor",
                                            "minor","minor"],
                                   "kind":["echo","echo","echo","echo","echo",
                                           "echo","echo","echo","echo","echo"],
                                   "name":["BUBOES","CONDUIT","DÉJÀ VU",
                                           "EXODUS","FOLLOWER","GLITCH",
                                           "HEX-EYE","THE RAVENING CALL",
                                           "STRANGE APPETITE","SIREN SONG"],
                                   "description":["Your skin blisters and bubbles. When you take Blood stress, take an extra D4 as the boils split and burst.",
                                                  "Your best efforts to keep the unreal energies of the Heart at bay are futile: your body is a crucible for strangeness. You cannot use Echo protection.",
                                                  "You notice minor elements of your past life appearing in the Heart as though it is reading your mind and adapting itself to your expectations; the GM tells you what happens.",
                                                  "You retch up a handful of writhing creatures: pallid fat moths, translucent grubs, spiders with the wrong number of legs, throbbing parasites and so on. Anyone who sees this and isn’t ready for it marks D4 stress to Mind.",
                                                  "Someone, or something, believes you are very important: chosen of the Heart and worth following. A weird-looking but essentially harmless creature or person follows you at a distance; they won’t approach you, but they’ll be keen to sift through your rubbish or attempt to hurt anyone who looks like they might want to get in your way.",
                                                  "You disappear, only reappearing after every other player has acted at least once.",
                                                  "Your vision swims as you start to perceive worlds other than your own layered on top of one another. Any action you take that requires accurate judging of distance (jumping, shooting, running down a corridor) becomes Risky. Once per session, you see something useful – ask the GM what it is.",
                                                  "This fallout has no effect, but it stays on your character, and occasionally manifests as a broken, staccato howl in the back of their mind. Should this fallout by upgraded, see THE RAVENING BEAST.",
                                                  "You crave unusual – taboo – things rather than good honest meat and drink: rusted metal, living creatures, vermin, effluvia, used clothing, beloved pets, etc. Next time you visit a haunt and attempt to refresh Blood or Mind stress, you must seek out this weirdness and indulge in it; otherwise you will be unable to refresh. Once you’ve sought out the weirdness, remove this fallout. This fallout can be upgraded into DARK CRAVINGS.",
                                                  "You cannot shake the thought of a particular place or person from your mind (the GM will pick a nearby landmark or NPC). If you do anything other than move towards it or remove obstacles in your path, the action becomes Risky. Once you reach it, the feeling dissipates."],
                                   "duration":["Ongoing","Ongoing",
                                               "Immediate, Ongoing",
                                               "Immediate","Ongoing",
                                               "Immediate","Ongoing","Ongoing",
                                               "Ongoing","Ongoing"]})

minor_fortune_fallout = pd.DataFrame({"level":["minor","minor","minor","minor",
                                               "minor","minor","minor","minor",
                                               "minor"],
                                      "kind":["fortune","fortune","fortune",
                                              "fortune","fortune","fortune",
                                              "fortune","fortune","fortune"],
                                      "name":["BROKEN","COLLATERAL",
                                              "FOREBODING","THE HARD WAY",
                                              "IN TROUBLE","LONG WAY ROUND",
                                              "SEPARATED","UNLUCKY",
                                              "WORD OF MOUTH"],
                                      "description":["An important item is damaged. You cannot use it until you take the time and resources to repair it.",
                                                     "The next time you mark stress, a nearby ally marks the same amount; you then remove this fallout.",
                                                     "Something bad is about to happen. GM, hint at an ominous future event – smoke in the distance, the tremors before a pulse, the frantic music of the Carnival. This fallout can be upgraded to CRISIS.",
                                                     "You lead the party into danger. The next obstacle the group attempts to overcome is Dangerous; they can reduce it to Risky, or even Standard, with a decent plan.",
                                                     "You upset an important figure in this or a nearby haven.",
                                                     "You take longer than expected to reach your target. On a delve, add D6 to the delve’s resistance. If you’re searching for someone or something in a landmark, you arrive just late enough to be in trouble.",
                                                     "You think you hear something, but when you turn to tell your allies, they are gone. You’ll have to track them down or hope they find you.",
                                                     "Things are going to get worse before they get better. You cannot use Fortune protection.",
                                                     "Word spreads of your misdeeds. Wherever you’re headed next, someone knows you’re going there, and is going to try to take advantage of you. The GM shows how word is spreading."],
                                      "duration":["Ongoing","Immediate",
                                                  "Ongoing","Immediate",
                                                  "Immediate, Ongoing",
                                                  "Immediate","Immediate",
                                                  "Ongoing","Immediate"]})

minor_supplies_fallout = pd.DataFrame({"level":["minor","minor","minor",
                                                "minor","minor","minor",
                                                "minor","minor"],
                                       "kind":["supplies","supplies",
                                               "supplies","supplies",
                                               "supplies","supplies",
                                               "supplies","supplies"],
                                       "name":["BROKEN","DAMAGED","DARKNESS",
                                               "DEBTOR","EMPTY","HALF RATIONS",
                                               "OUT OF AMMO","USED UP"],
                                       "description":["An important item is damaged. You cannot use it until you take the time and resources to repair it.",
                                                      "A resource you’re carrying is defective in some way – dented, torn, scuffed or cracked. Reduce its dice size by 1 step.",
                                                      "Your supplies of spireblack oil run low. All Delve or Discern checks you make become Risky. Another party member can remove this fallout by marking D6 stress to Supplies.",
                                                      "During the next session or later in this one, an NPC who lent you money will call in a favour.",
                                                      "You’re down to your last scraps of food, your last scraping of spireblack. You cannot use Supplies protection.",
                                                      "You’re running low on food. When you remove stress, roll two dice and pick the lowest of the two. Another party member can remove this fallout by marking D6 stress to Supplies.",
                                                      "You run out of ammunition for a ranged or powered weapon and it can no longer be used. If another party member has a similar weapon, they can remove this fallout by marking D6 stress to their own Supplies.",
                                                      "Your stocks are depleted of crucial items, something has spoiled or someone’s stolen something vital from your bag. You cannot use any healing items you own."],
                                       "duration":["Ongoing","Immediate",
                                                   "Ongoing","Immediate",
                                                   "Ongoing","Ongoing",
                                                   "Ongoing","Ongoing"]})

major_blood_fallout = pd.DataFrame({"level":["major","major","major","major",
                                             "major","major","major"],
                                    "kind":["blood","blood","blood","blood",
                                            "blood","blood","blood"],
                                    "name":["ARTERIAL WOUND","BLINDED",
                                            "BROKEN ARM","BROKEN LEG",
                                            "CRITICAL INJURY","DOWNED",
                                            "EXHAUSTED"],
                                    "description":["As BLEEDING, but you mark D6 stress at the end of every situation.",
                                                   "You can’t see, or can see so little that you might as well be blind. It might be permanent. Any task involving vision (so, most of them) becomes Dangerous.",
                                                   "Your arm breaks under the strain, and splintered bone juts up through your skin. You can’t use the arm until it heals, which will make some tasks Risky or Dangerous, and others impossible. This fallout can be downgraded to or upgraded from BATTERED.",
                                                   "Your leg bones splinter and crack. Any action involving the leg (climbing, moving above a crawl) automatically fails. This fallout can be downgraded to or upgraded from LIMPING.",
                                                   "You take a hit somewhere vital. The GM picks a skill you have access to and you no longer have access to that skill. For example, a hit to your sword-arm could remove Kill; an eye injury could remove Discern; ripped tendons in your fingers could remove Mend.",
                                                   "You can’t move under your own power and you’re barely clinging on to consciousness. You can be moved around by others, but without medical attention, you’re not going anywhere. Can be upgraded to DYING.",
                                                   "You can’t go on; if you push yourself any harder you’re going to pass out. Stop now, or convince someone else to carry you the rest of the way. Alternatively, make one more action and then fall unconscious once the roll is resolved."],
                                    "duration":["Ongoing","Ongoing",
                                                "Ongoing","Ogoing",
                                                "Ongoing","Ongoing",
                                                "Immediate, Ongoing"]})

major_mind_fallout = pd.DataFrame({"level":["major","major","major","major",
                                            "major","major","major","major"],
                                   "kind":["mind","mind","mind","mind","mind",
                                           "mind","mind","mind"],
                                   "name":["AETHERIC RESONANCE","ADDICT",
                                           "DELUSION","DESPAIR","MEMORY HOLES",
                                           "PHANTASM","SCARRED","UNSETTLING"],
                                   "description":["As COLLATERAL MAGIC Minor fallout, but you permanently learn AETHERIC SCOURGE and can cast it at will.",
                                                  "You realise that you have become reliant on drugs to keep yourself stable. When you’re high (or drunk, or whatever) you take Mind stress normally, but all tasks that require extended concentration or fine manipulation become Risky. When you’re not intoxicated and you suffer stress to Mind, roll twice and pick the higher dice. It takes a few minutes to get high and a few hours to sober up.",
                                                  "Something you believe to be true is in fact false. While you step outside, or during downtime, all the other players work with the GM to determine what you are deluded about. For example: you’re not an orphan, and you’ve got a family back in High Rise; there’s no such group as the Hounds, and your uniform doesn’t mean anything; etc. Next time you encounter the subject, reality (and the other characters) behave appropriately, leaving you confused and shaken.",
                                                  "Your mind races with the implications of what you’ve seen; your life before seems unreal and distant. The GM picks a domain that you have access to and you no longer have access to that domain.",
                                                  "You did things that you can’t quite recall. While you step outside, or during downtime, all the other players work with the GM to determine what you did that you blocked from your mind. These are generally pretty awful things. They can have happened up to a year ago in game time, or immediately upon suffering fallout. Your character has zero memory of the events, but everyone else involved knows what happened.",
                                                  "As FIGMENT, but the GM chooses a Major fallout instead.",
                                                  "Your mind cracks and reforms in primal, instinctive patterns. This functions as SHAKEN. In addition, every time you encounter the source of the fallout from now on, the GM can ask you to make an Endure check or suffer D8 stress to Mind.",
                                                  "You behave in a weird manner, causing your companions discomfort. This functions as SHAKEN, and any friendly character who sees you perform the act takes D6 Mind stress."],
                                   "duration":["Ongoing","Ongoing","Ongoing",
                                               "Ongoing","Immediate","Ongoing",
                                               "Ongoing","Immediate"]})

major_echo_fallout = pd.DataFrame({"level":["major","major","major","major",
                                            "major","major","major","major",
                                            "major","major"],
                                   "kind":["echo","echo","echo","echo","echo",
                                           "echo","echo","echo","echo","echo"],
                                   "name":["BLOODED","CULT","DARK CRAVINGS",
                                           "EYES","THE LIFE NOT LIVED","MEAT",
                                           "MIRAGE","THE RAVENING BEAST",
                                           "RECONFIGURED PHYSIOLOGY",
                                           "VANISHED"],
                                   "description":["You show some mark of the Heart in your physical form: twisting, fragile antlers of bone, fingernails that curve in fractal-sharp patterns, bioluminescent veins, additional joints in your limbs, and so on. Your frail mortal form is not designed to be used as such a canvas; when you mark stress to Blood, roll two dice and pick the higher.",
                                                  "Your actions mark you as a true scion of the Heart, and weird people/creatures will trail around you, espousing your glories (whether real or imagined). This is nothing but trouble, and any attempt to take advantage of them will go wrong. Getting into a haven will be difficult with this many people around, so you’d best hope that some of them die along the way.",
                                                  "As STRANGE APPETITE, but the effect is permanent until this fallout is removed.",
                                                  "Your eyes become wide black orbs; or perhaps you find more eyes blossoming on your body, growing in your sternum like a nest of spiders. You can see perfectly well in the dark, but lights dazzle and hurt you. The GM can call for an Endure check when you enter a well-lit area, and you take stress on a failure or partial success.",
                                                  "Upgrades DÉJÀ VU. You meet someone from your past who should, by all rights, be dead.",
                                                  "Everyone is just meat to you: dull, worthless, soulless. Any time you enter a situation where you must talk to a mundane NPC for an extended period of time, the GM can call for an Endure roll; on a failure, take D6 stress. If you are intimate with a mundane NPC, take D10 stress on a failure.",
                                                  "The next landmark you reach is a facsimile made by the Heart, arranged to give you what you want. It seems real, but the more you explore, the more obvious it is that everything – the streets, the books, the people – is fake. It’s an artful copy made out of meat, bone and blood. From the looks of things, it’s existed for hundreds of years. Once you realise that the landmark is fake, remove this fallout.",
                                                  "Emerging from a patch of shadows, the Ravening Beast that has been hiding in your mind appears. It will attempt to maul others, but its primary motivation is to consume you utterly. Fighting off the beast does not remove this fallout, but it has no further effect unless you upgrade this fallout.",
                                                  "Your organs and bones don’t make sense any more. You can no longer remove stress from Blood, or remove Blood fallout at haunts or through the use of medical kits. This shows itself in some outward fashion – unusual growths bulging under your skin, words appearing as bruises, black blood and so on.",
                                                  "The next landmark you reach isn’t there; you find something else instead. Presumably the landmark is somewhere, assuming it hasn’t been entirely swallowed up by the Heart."],
                                   "duration":["Ongoing","Ongoing",
                                               "Ongoing","Ogoing",
                                               "Immediate","Ogoing",
                                               "Immediate","Immediate",
                                               "Ongoing","Immediate"]})

major_fortune_fallout = pd.DataFrame({"level":["major","major","major","major",
                                               "major","major","major","major",
                                               "major","major","major"],
                                      "kind":["fortune","fortune","fortune",
                                              "fortune","fortune","fortune",
                                              "fortune","fortune","fortune",
                                              "fortune","fortune"],
                                      "name":["CRISIS","DESTROYED","EXILED",
                                              "GRIEVANCE","HELL FOR WEATHER",
                                              "LOST MAP","LOST PROPERTY",
                                              "NO WAY OUT","REPUTATION",
                                              "THE ROAD LESS TRAVELLED",
                                              "UNWILLING LEADER"],
                                      "description":["As FOREBODING, but now the danger actually occurs.",
                                                     "If you’re currently on a delve that has a connection established, remove the connection and describe what happened. If you’re inside a landmark, you destroy something of value and remove one of the landmark’s haunts (if it has any). Tell us how you did it (on purpose or accidentally).",
                                                     "You are banned from entering the haven you are currently in, or one that’s nearby – tell us what happened. Your allies aren’t subject to the same restrictions, but they will be treated with suspicion.",
                                                     "You are marked as an enemy by a group within the Heart – a cult, a church, the Hounds, members of a particular haven, beasts, etc. They will work to foil your efforts as best they can until you clear your name or kill your way out of the problem.",
                                                     "Your predictions were wrong and you lead the party into an actively dangerous area; or, the area you’re in changes and becomes hostile; or, if the locale permits, a storm whips up. Until you reach a landmark, all actions the party take become Risky. Remove this fallout when you do.",
                                                     "Your map is lost or stolen. Until you get it back or replace it, you cannot use connections – every journey is treated as unexplored territory.",
                                                     "You have misplaced an item; the GM picks which. You could spend time searching for it, but you’ll need to back-track – and someone might have made off with it already.",
                                                     "You lead the party into a dead-end, a trap or an ambush. Remove this fallout once you get out alive.",
                                                     "Another delver has gotten wind of your successes (or your weaknesses) and they are coming for you. You are ambushed by a hunter seeking to claim your head and relieve you of your hard earned supplies. Remove this fallout once the fight is over.",
                                                     "You pick the wrong path. The next landmark you reach isn’t the one you’re expecting – it’s an entirely different one, and probably one you were trying to avoid.",
                                                     "You end up responsible for an unwanted group – they have problems and they look to you to solve them. Maybe you killed their boss and now you’re the new boss; maybe they appeal to your sense of kindness and you foolishly give in; maybe the “group” is an orphan you have to look after. You can use the group to achieve things, but honestly, they cause more problems than they solve."],
                                      "duration":["Immediate","Immediate",
                                                  "Immediate, Ongoing",
                                                  "Immediate, Ongoing",
                                                  "Immediate, Ongoing",
                                                  "Ongoing","Immediate",
                                                  "Immediate","Immediate",
                                                  "Immediate",
                                                  "Immediate, Ongoing"]})

major_supplies_fallout = pd.DataFrame({"level":["major","major","major",
                                                "major","major","major"],
                                       "kind":["supplies","supplies",
                                               "supplies","supplies",
                                               "supplies","supplies"],
                                       "name":["IN THE DARK","LOST PROPERTY",
                                               "NO RATIONS",
                                               "SERVICES RENDERED","SOLD",
                                               "SPOILED"],
                                       "description":["Your torch sputters out, and you can’t re-light it. As DARKNESS, but someone or something also takes the opportunity to strike while you’re vulnerable. Until you can get some light, the fight is Dangerous. Once things calm down, another party member can remove this fallout by marking D6 stress to Supplies.",
                                                      "You have misplaced an item; the GM picks which. You could spend time searching for it, but you’ll need to back-track – and someone might have made off with it already.",
                                                      "You’re out of food. This functions as HALF RATIONS, and all actions you make become Risky due to shaking hands and low blood sugar. Another party member can remove this fallout by marking D8 stress to Supplies.",
                                                      "You’ve been forced to sell your skills to a third party to pay your debtors, and the work is not pleasant. Work out with the GM what your character doesn’t want to do but is prepared to do to make ends meet. If you don’t do it, you’ll be in trouble; alternatively, you’ve done it in the past, and you describe it in a flashback.",
                                                      "You’re forced to sell off something valuable to pay your debtors. Work out with the GM what you’re forced to sell. If you haven’t used it since you last visited a haven, you sold it retroactively.",
                                                      "A resource you are carrying is destroyed: it degrades into uselessness, is revealed to be fake, breaks in your pack or scatters on the ground. Remove it from your possessions."],
                                       "duration":["Immediate, Ongoing",
                                                   "Immediate","Ongoing",
                                                   "Immediate","Immediate",
                                                   "Immediate"]})

critical_blood_fallout = pd.DataFrame({"level":["critical","critical",
                                                "critical"],
                                       "kind":["blood","blood","blood"],
                                       "name":["BLEEDING OUT","CHOSEN",
                                               "GHOST"],
                                       "description":["You’re dying. Choose: do something useful before you die (and roll with mastery, because this is the last thing you’ll ever do) or desperately try to cling onto life (and lose something vital in the bargain).",
                                                      "You pass out and awaken in a half-dream state before the Heart; you have been blessed with its power. You return to life seemingly unharmed – a miracle! But within a session or two your transformation into an Angel, a nightmare creature of blistering unreality and scintillating ribbons of wet flesh, is complete. You’re not dead; but then again, you can’t die. You retire as a player character.",
                                                      "You die, but your spirit doesn’t rest easy. Your ghost remains in the City Beneath, angry at the manner of its death and the friends who it believes failed it – you haunt the party. Until they lay your spirit to rest (or murder it with specialised weapons), they suffer D6 Mind or Echo stress at the start of every session."],
                                       "duration":["Immediate","Ongoing",
                                                   "Immediate"]})

critical_echo_fallout = pd.DataFrame({"level":["critical","critical",
                                               "critical","critical",
                                               "critical","critical",
                                               "critical"],
                                      "kind":["echo","echo","echo","echo","echo",
                                              "echo","echo"],
                                      "name":["BEAST","BURST","DESCENT",
                                              "MESSIAH","PETRIFIED",
                                              "THE RAVENING","STRANDED"],
                                      "description":["Your body warps and changes beyond recognition: you become a protean mess of meat and bone, terrifying to behold. You disappear into the Heart, surfacing only as a legend whispered in deep shadows; those who knew you tell stories of your exploits to remember you and warn others. You will be seen again in future sessions: the GM can use the stats for a Greater Heartsblood Beast to represent you.",
                                                     "Unable to contain the energy (or parasites, or your alternate self) within your form any longer, your body ruptures like overripe fruit. If you’re lucky, you die; otherwise, you’re kept alive indefinitely, spread throughout the Heart. Anyone standing near you marks D6 stress to Echo.",
                                                     "The next time you’re in a landmark, the ground shakes as the Heart draws you and the place further down. Move the landmark, and anyone in it, to the next available space on the tier below. This is catastrophic; most people will not survive. You are swallowed up by the Heart, and retire as a player character.",
                                                     "You have been followed by a cult of weirdos and monsters for long enough now – something’s got to give. One of two things happen: either you believe your own hype and become a cult leader, leaving your life of delving behind and attempting to set up shop in a new haven within the Heart, or the cult out you as a false prophet and attempt to kill you in an appropriately brutal and public manner.",
                                                     "Your body calcifies, ossifies or crystalises, and you become a perfect statue of yourself. Your body is incredibly resistant to damage, so most people who turn into statues are left where they stand as a warning to others or as a sombre tribute.",
                                                     "Your body hatches with a wet red noise and a Ravening Beast emerges from you, skinless and steaming with heat, hungry for food. You die; this is how they breed. If your surviving friends are nearby, see boxout on p. 85 for Ravening Beast combat information.",
                                                     "Somewhere along the line, your reality diverged from everyone else’s – and by the time you realise, it’s too late to do anything about it. You are marooned in a fracture, an alternate future or a parasite dimension – tell the group about where you spend the rest of your life. You might return, but it’s doubtful that anyone you know will recognise you (or be alive) by the time you get back."],
                                      "duration":["Immediate","Immediate",
                                                  "Immediate","Immediate",
                                                  "Immediate","Immediate",
                                                  "Immediate"]})

critical_mind_fallout = pd.DataFrame({"level":["critical","critical",
                                               "critical"],
                                      "kind":["mind","mind","mind"],
                                      "name":["ABANDON","BREAK","OBSESSED"],
                                      "description":["You have taken complete leave of your senses after the horrors that the Heart has laid upon you. You wander off into the wilderness; if you return, you will not be recognisable. More likely, you will starve to death in a cellar.",
                                                     "You completely lose it. Anyone standing nearby who you care about marks D8 stress to Mind; anyone standing nearby who you’ve never really liked marks D8 stress to Blood as you attack them. After this, you die (either self-inflicted or at the hands of your allies) or your mind is so shattered that you retire as a player character.",
                                                     "Your purpose has become twisted and cruel; you will stop at nothing to achieve it. Your character is retired from play and becomes an antagonist that acts against the surviving player characters in an effort to achieve their wicked desires."],
                                      "duration":["Immediate","Ongoing",
                                                  "Immediate, Ongoing"]})

critical_fortune_fallout = pd.DataFrame({"level":["critical","critical",
                                                  "critical","critical"],
                                         "kind":["fortune","fortune",
                                                 "fortune","fortune"],
                                         "name":["FOOL’S GOLD",
                                                 "HEAVY HANGS THE HEAD",
                                                 "A SLOW AND INSIDIOUS KILLER",
                                                 "WRONG PLACE"],
                                         "description":["You get exactly what you want – secrets, penitence, freedom, whatever. It seems too good to be true, which is apt, because it isn’t: you’ve been tricked or deluded, and you don’t have it after all. The stress is too much for you to bear, and your only worth now is as a warning to other delvers not to take things at face value.",
                                                        "Despite your best efforts, you are elected leader of a haven; maybe you defend it from an attack and the people think you’ve got what it takes to run the place. You don’t. You have the capacity to do one useful thing with the haven’s resources before you’re assassinated by your rivals, the haven is overrun or the fact you were a patsy all along is revealed and you’re hung out to dry.",
                                                        "You act with unearned confidence and your hubris is rewarded with an ironic death.",
                                                        "You accidentally take a fatal blow meant for someone else. They are unharmed; you die."],
                                         "duration":["Immediate","Immediate",
                                                     "Immediate","Immediate"]})

critical_supplies_fallout = pd.DataFrame({"level":["critical","critical",
                                                   "critical","critical"],
                                          "kind":["supplies","supplies",
                                                  "supplies","supplies"],
                                          "name":["DEFENCELESS","PITCH BLACK",
                                                  "PLUMMET","STARVATION"],
                                          "description":["Your shield shatters; your sword breaks when struck by an enemy; or your armour straps rip and come apart. Unable to hold your foes off for any longer, you are run through or mauled and left for dead.",
                                                         "Unable to see, you are dragged away by darkling creatures, never to return.",
                                                         "Your line snaps; your hooks don’t hold; your pick shears away and tumbles into a chasm. Whatever it is, you plunge into the darkness beneath and do not return.",
                                                         "You starve to death or are overcome by dehydration."],
                                          "duration":["Immediate","Immediate",
                                                      "Immediate",
                                                      "Immediate"]})

blood_fallout = pd.concat([minor_blood_fallout,major_blood_fallout,
                           critical_blood_fallout], ignore_index=True)

mind_fallout = pd.concat([minor_mind_fallout,major_mind_fallout,
                          critical_mind_fallout], ignore_index=True)

echo_fallout = pd.concat([minor_echo_fallout,major_echo_fallout,
                          critical_echo_fallout], ignore_index=True)

fortune_fallout = pd.concat([minor_fortune_fallout,major_fortune_fallout,
                             critical_fortune_fallout], ignore_index=True)

supplies_fallout = pd.concat([minor_supplies_fallout,major_supplies_fallout,
                              critical_supplies_fallout], ignore_index=True)

minor_fallout = pd.concat([minor_blood_fallout,minor_mind_fallout,
                           minor_echo_fallout,minor_fortune_fallout,
                           minor_supplies_fallout], ignore_index=True)

major_fallout = pd.concat([major_blood_fallout,major_mind_fallout,
                           major_echo_fallout,major_fortune_fallout,
                           major_supplies_fallout], ignore_index=True)

critical_fallout = pd.concat([critical_blood_fallout,critical_mind_fallout,
                              critical_echo_fallout,critical_fortune_fallout,
                              critical_supplies_fallout], ignore_index=True)

fallout_df = pd.concat([minor_fallout,major_fallout,critical_fallout],
                       ignore_index=True)

def main():
    if __name__ == '__main__':
        print("Well, well well. If it isn't the consequences to your actions.")
    return

if __name__ == '__main__':
    main()
